name: Actions Workflow
on: [push]
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple js Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Yash
      - name: Log greeting time
        run: echo "{{  steps.greet.time  }}"

        

    