name: cron-commands
on:
  repository_dispatch:
    types: [build1]
  # schedule:
  #   - cron: "0/6 * * * *"
  pull_request:
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: Access github payload from api
        run: |
          echo ${{  github.event.client_payload  }}
      - name: echo a string
        run: echo "Inside  a job(Inside a steps )"
      - name: multiline shell-commands
        run: |
          npm -v
          node -v
      - name: Python shell-commands
        run: |
          import platform
          print(platform.processor())
        shell: python